=== W3D3/DiffVisualizer/server/diffpairlist_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Diff Pair List",
  "description": "A list of diff pairs",
  "type": "array",
  "items": {
    "type": "object",
  	"properties": {
      "id": {
        "description": "Id of the diffpair",
        "type": ["integer", "string"]
      },
      "baseUrl": {
        "description": "URL of the repo",
        "type": "string",
        "format": "uri"
      },
      "commit": {
        "description": "The hash of the selected commit",
        "type": "string"
      },
        "parentCommit": {
        "description": "The hash of the selected parent commit",
        "type": "string"
      },
        "srcFileName": {
        "description": "The path to the src file, relative to baseUrl",
        "type": "string"
      },
        "dstFileName": {
        "description": "The path to the dst file, relative to baseUrl",
        "type": "string"
      }
    },
    "required": [ "id", "baseUrl", "commit", "parentCommit", "srcFileName", "dstFileName" ]
  }
}

=== W3D3/DiffVisualizer/sampledata/simple.json
[{
        "id": 1,
        "baseUrl": "https://github.com/W3D3/difftest/",
        "parentCommit": "ae44ba99958d60edff49b8f8f30db20bf40a499b",
        "commit": "71d35fa444443683714eac9d87136a7810076255",
        "srcFileName": "Test.java",
        "dstFileName": "Test.java"
    },
    {
        "id": 2,
        "baseUrl": "https://github.com/apache/commons-lang/",
        "parentCommit": "f059e5f7fa1ac4a906b5d2e18d72d410bf28fa2d",
        "commit": "dfecbe970917754511a081f8b86efac211e624f6",
        "srcFileName": "src/main/java/org/apache/commons/lang3/LocaleUtils.java",
        "dstFileName": "src/main/java/org/apache/commons/lang3/LocaleUtils.java"
    },
    {
        "id": 3,
        "baseUrl": "https://github.com/apache/commons-lang/",
        "parentCommit": "f059e5f7fa1ac4a906b5d2e18d72d410bf28fa2d",
        "commit": "dfecbe970917754511a081f8b86efac211e624f6",
        "srcFileName": "src/main/java/org/apache/commons/lang3/LocaleUtils.java",
        "dstFileName": "src/main/java/org/apache/commons/lang3/NotTheSame.java"
    },
    {
        "id": 230,
        "commit": "281d600ae2f9ba6c6bc7bee0e8025698b9a76563",
        "parentCommit": "8f960ea356f68dad475658ff43af342d753a57a6",
        "srcFileName": "activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/MessageDatabase.java",
        "dstFileName": "activemq-kahadb-store/src/main/java/org/apache/activemq/store/kahadb/MessageDatabase.java",
        "baseUrl": "https://github.com/apache/activemq"
    }
]
